## EDA: iris dataset - part 1: Basic exploration

### Preparations

Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

1) Load iris dataset as iris:

In [2]:
# Load the iris dataset
iris = pd.read_csv(r"DSA_iris_dataset.csv")
iris.head(10)

,sepal length (cm),sepal width (cm),petal l. / cm,petal w. / cm,target,species
0,5.1,3.5,1.4,0.2,NaN,setosa
1,4.9,3.0,1.4,0.2,NaN,setosa
2,4.7,3.2,1.3,0.2,NaN,setosa
3,4.6,3.1,1.5,0.2,NaN,setosa
4,5.0,3.6,1.4,0.2,NaN,setosa
5,5.4,3.9,1.7,0.4,NaN,setosa
6,4.6,3.4,1.4,0.3,NaN,setosa
7,5.0,3.4,1.5,0.2,NaN,setosa
8,4.4,2.9,1.4,0.2,NaN,setosa
9,4.9,3.1,1.5,0.1,NaN,setosa

2) Overview: head, size, shape, info...

In [3]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal l. / cm      150 non-null    float64
 3   petal w. / cm      150 non-null    float64
 4   target             0 non-null      float64
 5   species            150 non-null    str
dtypes: float64(5), str(1)
memory usage: 8.4 KB

3) Quick statistics and summary (value_counts, max, min, describe, nlargest, nsmallest, nunique):

In [4]:
iris.describe()

,sepal length (cm),sepal width (cm),petal l. / cm,petal w. / cm,target
count,150.000000,150.000000,150.000000,150.000000,0.0
mean,5.843333,3.309333,3.758000,1.199333,NaN
std,0.828066,3.208637,1.765298,0.762238,NaN
min,4.300000,2.000000,1.000000,0.100000,NaN
25%,5.100000,2.800000,1.600000,0.300000,NaN
50%,5.800000,3.000000,4.350000,1.300000,NaN
75%,6.400000,3.300000,5.100000,1.800000,NaN
max,7.900000,42.000000,6.900000,2.500000,NaN

In [5]:
iris.nunique(axis=0)

sepal length (cm)    35
sepal width (cm)     23
petal l. / cm        43
petal w. / cm        22
target                0
species               3
dtype: int64

In [6]:
iris["sepal width (cm)"].nlargest(5)

33    42.0
15     4.4
32     4.1
14     4.0
5      3.9
Name: sepal width (cm), dtype: float64

4) Missing data (isnull) and duplicates (duplicated)

In [7]:
iris.duplicated().sum()

np.int64(1)

In [8]:
iris[iris.duplicated()] # avoid unnecesary conditions with Booleans, e.g. iris[iris.duplicated()==True]

,sepal length (cm),sepal width (cm),petal l. / cm,petal w. / cm,target,species
142,5.8,2.7,5.1,1.9,NaN,virginica

5) Drop unnecessary columns and rename columns

In [9]:
iris.drop(["target"], axis=1, inplace=True)

In [10]:
iris.rename(columns={"petal l. / cm":"petal length (cm)", "petal w. / cm":"petal width (cm)"}, inplace=True)

In [11]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [12]:
iris["sepal width (cm)"].nlargest(3)

33    42.0
15     4.4
32     4.1
Name: sepal width (cm), dtype: float64

In [13]:
iris.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [14]:
iris.drop_duplicates()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [15]:
iris["sepal width (cm)"].idxmax()

33

Change the wrong value (42.0 sepal widht) to 4.2:

In [16]:
# iris.iloc[iris["sepal width (cm)"].idxmax(),iris.columns.get_loc("sepal width (cm)")]=4.2

In [17]:
iris.loc[33, "sepal width (cm)"] = 4.2

In [18]:
iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

6) Export cleaned dataset as "DSA_iris_cleaned.csv" into the same folder

In [19]:
iris.to_csv("DSA_iris_cleaned.csv", index=False)