# Pandas puzzles

Most the following exercises have been selected by UZH ZI & David Pinezich as part of the ZI APPD course. Inspired by [100 Numpy exerises](https://github.com/rougier/numpy-100), here is a short list of puzzles for testing your knowledge of [pandas'](http://pandas.pydata.org/) power. 

Since pandas is a large library with many different specialist features and functions, these excercises focus mainly on the fundamentals of manipulating data (indexing, grouping, aggregating), making use of the core DataFrame and Series objects. 

Many of the excerises here are stright-forward in that the solutions require no more than a few lines of code (in pandas or NumPy). Choosing the right methods and following best practices is the underlying goal.

If you're just starting out with pandas and you are looking for some other resources, the official documentation  is very extensive. In particular, some good places get a broader overview of pandas are...

- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [pandas basics](http://pandas.pydata.org/pandas-docs/stable/basics.html)
- [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)
- [cookbook and idioms](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

Enjoy!

## Importing pandas

### Getting started and checking your pandas setup

**1.** Import pandas under the name `pd`.

In [1]:
import pandas as pd
import numpy as np

**2.** Print the version of pandas that has been imported.

In [2]:
pd.__version__

'2.3.3'

**3.** Print out all the version information of the libraries that are required by the pandas library.
(**hint**: show_versions()

In [5]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.9.10
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.26100
machine               : AMD64
processor             : Intel64 Family 6 Model 170 Stepping 4, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : German_Switzerland.1252

pandas                : 2.3.3
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : None
Cython                : None
sphinx                : None
IPython               : 8.18.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.14.2
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.4.2
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [152]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data = data, index = labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Display a summary of the basic information about this DataFrame and its data.
(**hint**: df.describe)

In [8]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**6.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [16]:
animals = df[["animal", "age"]]
print(animals)

selection = df.iloc[:,:2]
selection

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**7.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.
(**hint**: df.index)

In [23]:
selected_rows = df.loc[df.index[[3,4,8]], ["animal", "age"]]
selected_rows

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**8.** Select only the rows where the number of visits is greater than 2.

In [25]:
df.loc[df["visits"] > 2]

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

**9.** Select the rows where the age is missing, i.e. is `NaN`.
(**hint**: Series.isnull)

In [26]:
df.loc[df["age"].isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**10.** Select the rows where the animal is a cat *and* the age is less than 3.

In [28]:
df.loc[(df["animal"] == "cat") & (df["age"] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**11.** Select the rows the age is between 2 and 4 (inclusive).

In [34]:
df.loc[(df["age"] > 1) & (df["age"] <= 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**12.** Calculate the sum of all visits (the total number of visits).

In [36]:
df["visits"].sum()

np.int64(19)

**13.** Calculate the mean age for each different animal in `df`.

In [37]:
df["age"].mean()

np.float64(3.4375)

**14.** Append a new column 'newcol' to `df` with your choice of values for each column. Then delete that column to return the original DataFrame.

In [44]:
df["k"]= df["age"]
print(df)
df = df.drop(columns = "k")
df

  animal  age  visits priority    k
a    cat  2.5       1      yes  2.5
b    cat  3.0       3      yes  3.0
c  snake  0.5       2       no  0.5
d    dog  NaN       3      yes  NaN
e    dog  5.0       2       no  5.0
f    cat  2.0       3       no  2.0
g  snake  4.5       1       no  4.5
h    cat  NaN       1      yes  NaN
i    dog  7.0       2       no  7.0
j    dog  3.0       1       no  3.0

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**15.** Append a new row to `df` for a 5 y.o. parrot on his second visit with no priority. Then delete that row again to return to the original DataFrame.

In [149]:
parrot = {"animal": "parrot", "age": 5, "visits": 2, "priority": "no"}
df2 = df._append(parrot, ignore_index=True)
print(df2)
# or ignoring the index:
df.loc[len(df.index)] = ["parrot", 5, 2, "no"]
df

    animal  age  visits priority
0      cat  2.5       1      yes
1      cat  3.0       3      yes
2    snake  0.5       2       no
3      dog  NaN       3      yes
4      dog  5.0       2       no
5      cat  2.0       3       no
6    snake  4.5       1       no
7      cat  NaN       1      yes
8      dog  7.0       2       no
9      dog  3.0       1       no
10  parrot  5.0       2       no

    animal  age  visits priority
a      cat  2.5       1      yes
b      cat  3.0       3      yes
c    snake  0.5       2       no
d      dog  NaN       3      yes
e      dog  5.0       2       no
f      cat  2.0       3       no
g    snake  4.5       1       no
h      cat  NaN       1      yes
i      dog  7.0       2       no
j      dog  3.0       1       no
10  parrot  5.0       2       no

**16.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [153]:
# different solutions possible:

def our_mapping(x):
    if x == "yes":
        return True
    return False
df_copy1 = df.copy()
df_copy2 = df.copy()
print(df)
df['priority'] = df['priority'].replace(["yes", "no"], [True, False])
print(df)
df_copy1['priority'] = df_copy1['priority'].map({'yes': True, 'no': False})
print(df_copy1)
df_copy2['priority'] = df_copy2['priority'].map(our_mapping)
df_copy2

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False
  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

C:\Users\jschoer\AppData\Local\Temp\ipykernel_34832\1552752532.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['priority'] = df['priority'].replace(["yes", "no"], [True, False])

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

**17.** In the 'animal' column, change the 'snake' entries to 'python'.

In [53]:
df["animal"] = df["animal"].replace("snake", "python")
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  2.0       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no