In [48]:
import pandas as pd

In [49]:
solids = pd.read_csv(r"C:\Users\jschoer\Desktop\DSA103development\ChemicalDataScience103\lectures\session07\materials\inventory_solids.csv")

In [50]:
solids

             Name  sum formula   amount(g)
0  sodium sulfate       Na2SO4         980
1  copper acetate       CuOAc2         100
2         quinine   C20H24N2O2          45
3  copper acetate       CuOAc2          32
4  copper bromide         CuBr          56
5  copper acetate       CuOAc2         250

In [51]:
solids.columns = ["name", "sum_formula", "amount(g)"]
solids

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate       CuOAc2        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56
5  copper acetate       CuOAc2        250

In [52]:
solids.values[1]

array(['copper acetate', ' CuOAc2', 100], dtype=object)

In [53]:
solids.iloc[:,1]

0         Na2SO4
1         CuOAc2
2     C20H24N2O2
3         CuOAc2
4           CuBr
5         CuOAc2
Name: sum_formula, dtype: str

In [54]:
solids["amount(mg)"] = solids["amount(g)"]*1000
solids["amount(kg)"] = solids["amount(g)"]/1000
solids

             name  sum_formula  amount(g)  amount(mg)  amount(kg)
0  sodium sulfate       Na2SO4        980      980000       0.980
1  copper acetate       CuOAc2        100      100000       0.100
2         quinine   C20H24N2O2         45       45000       0.045
3  copper acetate       CuOAc2         32       32000       0.032
4  copper bromide         CuBr         56       56000       0.056
5  copper acetate       CuOAc2        250      250000       0.250

In [55]:
solids.drop([1],axis=0,inplace=True)

In [56]:
solids.drop(columns=["amount(kg)"], inplace=True)

In [57]:
solids.drop(["amount(mg)"], axis=1, inplace=True)

In [58]:
solids.loc[len(solids)] = ["Sodium chloride", "NaCl", 100]

In [59]:
solids

              name  sum_formula  amount(g)
0   sodium sulfate       Na2SO4        980
2          quinine   C20H24N2O2         45
3   copper acetate       CuOAc2         32
4   copper bromide         CuBr         56
5  Sodium chloride         NaCl        100

In [60]:
solids.drop([4,5], inplace=True)

In [61]:
solids

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32

In [62]:
solids2 = pd.read_csv("inventory_solids.csv")
solids2.columns = ["name", "sum_formula", "amount(g)"]

In [63]:
solids3 = pd.concat([solids, solids2],ignore_index=True, axis=0)
solids3

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1         quinine   C20H24N2O2         45
2  copper acetate       CuOAc2         32
3  sodium sulfate       Na2SO4        980
4  copper acetate       CuOAc2        100
5         quinine   C20H24N2O2         45
6  copper acetate       CuOAc2         32
7  copper bromide         CuBr         56
8  copper acetate       CuOAc2        250

In [64]:
solids3.to_csv("completeinventory.csv", index=False)

In [65]:
solids3.iloc[solids3["amount(g)"].idxmax(),:]

name           sodium sulfate
sum_formula            Na2SO4
amount(g)                 980
Name: 0, dtype: object

In [66]:
solids3.groupby("name").sum()

                                 sum_formula  amount(g)
name
copper acetate   CuOAc2 CuOAc2 CuOAc2 CuOAc2        414
copper bromide                          CuBr         56
quinine                C20H24N2O2 C20H24N2O2         90
sodium sulfate                 Na2SO4 Na2SO4       1960

In [67]:
solids3.describe()

        amount(g)
count    9.000000
mean   280.000000
std    402.637244
min     32.000000
25%     45.000000
50%     56.000000
75%    250.000000
max    980.000000

In [68]:
solids3.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         9 non-null      str
 1   sum_formula  9 non-null      str
 2   amount(g)    9 non-null      int64
dtypes: int64(1), str(2)
memory usage: 531.0 bytes

In [69]:
solids3

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1         quinine   C20H24N2O2         45
2  copper acetate       CuOAc2         32
3  sodium sulfate       Na2SO4        980
4  copper acetate       CuOAc2        100
5         quinine   C20H24N2O2         45
6  copper acetate       CuOAc2         32
7  copper bromide         CuBr         56
8  copper acetate       CuOAc2        250

In [70]:
solids3["newamount"] = solids3["amount(g)"].apply(lambda x: x + 111)
solids3

             name  sum_formula  amount(g)  newamount
0  sodium sulfate       Na2SO4        980       1091
1         quinine   C20H24N2O2         45        156
2  copper acetate       CuOAc2         32        143
3  sodium sulfate       Na2SO4        980       1091
4  copper acetate       CuOAc2        100        211
5         quinine   C20H24N2O2         45        156
6  copper acetate       CuOAc2         32        143
7  copper bromide         CuBr         56        167
8  copper acetate       CuOAc2        250        361